# Generated by Django 6.0.6 on 2026-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(default='PEFA Thika Road Sanctuary', max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, default='Anonymous', max_length=150)),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('prayer_items', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed_by_pastor', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('preacher', models.CharField(default='Senior Pastor', max_length=150)),
                ('service_type', models.CharField(choices=[('SUNDAY', 'Sunday Main Service'), ('MIDWEEK', 'Mid-Week Midweek Service'), ('YOUTH', 'Youth Fellowship Explosion'), ('CONFERENCE', 'Special Ministry Conference')], default='SUNDAY', max_length=20)),
                ('date_preached', models.DateField()),
                ('summary', models.TextField(help_text='Brief summary of the sermon keys and scripture anchors.')),
                ('youtube_url', models.URLField(blank=True, help_text='Paste live streaming or recording link.', null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Upload MP3 format for local listening downloads.', null=True, upload_to='sermons/audio/')),
            ],
            options={
                'ordering': ['-date_preached'],
            },
        ),
    ]
