# Generated by Django 6.0.6 on 2026-07-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_churchimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchGalleryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a caption for the slide activity (e.g., Sunday Main Worship)', max_length=200)),
                ('image', models.ImageField(help_text='Upload landscape-oriented sanctuary lifestyle pictures', upload_to='church_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
