# Generated by Django 6.0.6 on 2026-08-18 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_churchgalleryasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'Lipa Na M-Pesa Online (STK)'), ('C2B', 'Paybill Manual SIM Toolkit Entry'), ('B2C', 'Pastoral Welfare / Disbursement Outward')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('account_reference', models.CharField(help_text='e.g., Tithe, Building Fund, Welfare Remarks', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Implementation'), ('COMPLETED', 'Completed Glory Payment'), ('FAILED', 'Failed / Cancelled / Insufficient')], default='PENDING', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
