# Generated by Django 6.0.6 on 2026-08-18 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mpesatransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Sanctuary Roofing Extension Phase 2', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated url identifier token.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the vision and why the cathedral needs it.')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Total budget goal in KES.', max_digits=12)),
                ('cover_image', models.ImageField(help_text='Upload high-res architecture design or site snapshot.', upload_to='projects/covers/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to archive completed or paused projects.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
